pipeline {
		agent any	
		stages{
				stage('Checkout Code'){
					steps{
							checkout scm
					}
				}
				stage('Build'){
					steps{
							bat "cd web && mvn clean install -Dmaven.test.skip=true"
					}
				}
				stage('Mostrar SCANNER_HOME') {
				    environment {
				        SCANNER_HOME = tool 'ingreq-sonar-scanner'
				    }
				    steps {
				        script {
				            echo "El directorio SCANNER_HOME es: $SCANNER_HOME"
				        }
				    }
				}
				stage('SonarQube analysis') {
					steps {
				       script{
				           withSonarQubeEnv(credentialsId: 'jifjenkins', installationName: 'sonarqube-ingreq'){
				              sh "C:\Users\swhm9\.jenkins\tools\hudson.plugins.sonar.SonarRunnerInstallation\ingreq-sonar-scanner\bin\sonar-scanner -Dsonar.projectKey=web -Dsonar.sources=. "
				            }
				       }
				    }
				
				  }
				stage('SQuality Gate') {
				  steps {
				       timeout(time: 1, unit: 'MINUTES') {
				       		waitForQualityGate abortPipeline: true
				       }
				  }
				}		
				
				stage('Archive Artifact'){
					steps{
							archiveArtifacts artifacts:'web/target/*.war'
					}
				}
				stage('deployment'){
					steps{
							bat "cd web && mvn clean install -Dmaven.test.skip=true"
					}
				}
		}
}
		