pipeline {
		agent any
		
		stages{
				stage('Checkout Code'){
					steps{
							checkout scm
					}
				}
				stage('Build'){
					steps{
							bat "cd web && mvn clean install -Dmaven.test.skip=true"
					}
				}
				stage('Archive Artifact'){
					steps{
							archiveArtifacts artifacts:'web/target/*.war'
					}
				}
				stage('deployment'){
					steps{
							archiveArtifacts artifacts:'web/target/*.war'
					}
				}
		}
}
		