pipeline {
		agent any
		
		stages{
				stage('Checkout Code'){
					steps{
							checkout scm
					}
				}
				stage('Build'){
					steps{
							bat "cd web && mvn clean install -Dmaven.test.skip=true"
					}
				}
				stage('Archive Artifact'){
					steps{
							archiveArtifacts artifacts:'web/target/*.war'
					}
				}
				stage('deployment'){
					steps{
						deploy adapters: [tomcat9(url: 'http://13.38.8.24:8080/',credentialsId: 'tomcatCreds')],
						war: 'web/target/*.war',
						contextPath: 'app'
					}
				}
		}
}
		